const SENITY_PROJECT_ID = process.env.SENITY_PROJECT_ID;
const SENITY_DATASET = process.env.SENITY_DATASET;
const SENITY_API_VERSION = process.env.SENITY_API_VERSION;
const SENITY_TOKEN = process.env.SENITY_TOKEN;

export { SENITY_PROJECT_ID, SENITY_DATASET, SENITY_API_VERSION, SENITY_TOKEN }